### PR TITLE
Add musl libc compatibility

### PR DESCRIPTION
**Pull request by Archetypic**

### CODE REVIEW

**Comment by leo-arch** [comment]
Thanks for your PR @Archetypic! It seems to be fine.
How are you compiling exactly? I need to add this info to the docs.

**Comment by Archetypic** [comment]
I use the supplied `Makefile` which is sufficient.

```
make -j$(nproc)
```

**Comment by leo-arch** [comment]
So, you can confirm it works fine on Void?

For my part, I tried to compile with `musl` and got a bunch of complains about readline's lib and a few about `acl.h` and `capability.h`. I guess Void ships these libraries, though they're not available for `musl` (at least not in my systems).

**Comment by Archetypic** [comment]
Void has `libcap-devel`, `readline-devel`, and `acl-devel`.

Though they do not have `libmagic-devel` which provides the `magic.h`. This is not an issue about musl but that GNU/Linux distribution lacking a required package for the compilation of CliFM.

**Comment by leo-arch** [comment]
Good to know. Just in case you didn't know, some distributions provide `magic.h` with the `file` package (Arch), while others (like Debian) do it with `libmagic-devel`.

Anyway, the important thing is that CliFM works on Void. 

Let me know if some issue comes up.

**Pull request merged**
