### PR TITLE
new plugin fzcd

### PR DESCRIPTION
**Pull request by Docbroke**
change directory using fzf

### CODE REVIEW

**Comment by leo-arch** [comment]
Cool! I like it; pretty useful.

Give me a few hours (I'm really tired now, almost zero sleep) to try a few tweaks to make it look consistent with the remaining plugins (mostly colors), and remove those things that do not properly work on a non-Unicode, 16 colors terminals (specially the spinner).

You can do this yourself though: just make sure it will run with no displaying issues on a very basic terminal (I mostly use `Aterm` for this kind of testing), and that `shellcheck` spells out no warnings.

Another thing: not all distros provide an up to date package for `fzf`. Some flags might not work in older versions of `fzf`. I myself still need to check this for almost all plugins.

One more thing: TAB and the Right arrow key could be used to accept the highlighted entry too.

EDIT: still another thing. What command do you want to bind this plugin to? I'm using `=`, but only for testing purposes. It could be whatever you consider more appropriate.

**Comment by Docbroke** [comment]
I am using `ff`. It is quick to type, f for fzf, f for fm.

**Comment by Docbroke** [comment]
added right arrow key to accept selection.

**Comment by Docbroke** [comment]
if we use `find . -type f` , this script can be an alternative to `finder.sh`, with ability to search files in sub-folders also. I have modified finder.sh for my personal use that way.

btw., parsing output of `ls` is not safe for scripts http://mywiki.wooledge.org/ParsingLs

**Pull request merged**
