### PR TITLE
Multi file

### PR DESCRIPTION
**Pull request by sundaran1122**
moved global variables to globals.c
and moved #defines to helpers.h

### CODE REVIEW

**Comment by sundaran1122** [comment]
we still have a lot of work to do

**Comment by leo-arch** [comment]
Last night I got the whole thing working: the single source file is now split into 25 (or more) c files. I'm using a central header file (includes, defines, and globals, as extern) and files organized by feature/function. I hope to finish the work today to push it to the test branch.

**Comment by sundaran1122** [comment]
this will make maintaining it a lot easier

**Comment by leo-arch** [comment]
The only thing I observed is that, after splitting the source file, it results in a bigger binary size: 460K before splitting, 650 or so after, and there's no new code at all. It isn't significant, but...

**Comment by sundaran1122** [comment]
its prob due to all the linking

**Comment by leo-arch** [comment]
Ok. The first version is ready: the code is now split into 30 files, including headers (starting at main.c). Take a look at it (testing branch) and tell me what you think. I'm sure much could be improved, but is a good way to start (it compiles ok and works).

**Comment by sundaran1122** [comment]
pretty nice already!

**Comment by sundaran1122** [comment]
there is still some stuff to do

**Pull request closed without merging**
