### PR TITLE
every souce file now has its own header file

### PR DESCRIPTION
**Pull request by sundaran1122**
title

this probably broke freebsd compatibility but after fixing that this branch canbe merged into master

### CODE REVIEW

**Comment by leo-arch** [comment]
Thanks. I'll try this as soon as I can. Why do you say that FreeBSD compatibility might be broken?

**Comment by sundaran1122** [comment]
ioctl

**Comment by sundaran1122** [comment]
by this branch I mean orgin/testing not sundaran1122/testing btw

**Comment by leo-arch** [comment]
I finally got it working on FreeBSD: a few libraries needed to be added conditionally in some c files, and two lines were modified in src/Makefile (":=" by "!=" and "$^" by "${OBJS}") to make it work on FreeBSD as well. Merging.

**Pull request merged**
