### PR TITLE
give proper height to fzfnav preview

### PR DESCRIPTION
**Pull request by Docbroke**

### CODE REVIEW

**Comment by leo-arch** [comment]
Hi @Docbroke. Why to make `fzf` take only 80% of the screen's height? What's the advantage over 100%?

**Comment by Docbroke** [comment]
with 80% clifm interface remains visible, with 100% it is only fzf.
I am fine with both actually. 
Note: file list needs to be updated when fzfnav exits, it gets cleared.

**Comment by leo-arch** [comment]
I see your point: we should avoid the impression of fzf running as a separate program. However, since both heights are fine, I guess an option (say `FzfHeight`) could be added to the configuration file (`BFG.cfm`).

The cleared screen issue is fixed replacing the `printf` line at the end of `fzfnav.sh` by this:

```sh
_lines=${LINES:-100}
printf "\033[%dM" "$_lines"
```

EDIT: The height issue, as you put it, applies to almost all plugins running `fzf`.

**Comment by Docbroke** [comment]
FzfHeight is fine edition.
cleared screen issue is not solved by those lines.

**Comment by leo-arch** [comment]
It works better when `fzf` height isn't set to 100%.
The thing is that the screen gets cleared as soon as taken by `fzf` itself. In other words, it is `fzf` itself what clears the screen.

**Comment by Docbroke** [comment]
Yes, changing back to 80% with those two lines, solves cleared screen issue.

**Comment by leo-arch** [comment]
Great. I'll add the height option to `BFG.cfm` to see how it behaves. I'll let you know.

**Comment by leo-arch** [comment]
Done. Let me know if it works for you.
Closing this PR to avoid conflicts with master.

**Pull request closed without merging**
