### PR TITLE
added _clang-format for automatic formatting

### PR DESCRIPTION
**Pull request by sundaran1122**

### CODE REVIEW

**Comment by sundaran1122** [comment]
# basic tutorial
1. install clang(obviously)
2. cd into src and run `clang-format -i -style=file <file>`

# explanation
`-style=file` tells clang-format that we are using a custom style rather than the in built style

`-i` tell clang-format to change the files in place rather than output the output to stdout

# integration
for other text editors you have to use a plugin

for vim it has an in-build code formatter(differant from the code indenter`=`). 

in order to use clang-format as formatter add this to your vimrc(or `ftplugin/c.vim`)
``` vimscript
set formatprg="clang-format -style=file"
```
now run `gq<textobject or motion>`.

**Comment by sundaran1122** [comment]
also are any changes needed to the code style?

looks kinda like this(tabs)
``` c
/* Returns the string after the first appearance of a given char, or
 * returns NULL if C is not found in STR or C is the last char in STR. */
char *
straft(char *str, const char c)
{
	if (!str || !*str || !c)
		return (char *)NULL;

	char *p = str, *q = (char *)NULL;

	while (*p) {
		if (*p == c) {
			q = p;
			break;
		}
		p++;
	}

	/* If C was not found or there is nothing after C */
	if (!q || !*(q + 1))
		return (char *)NULL;

	char *buf = (char *)malloc(strlen(q));

	if (!buf)
		return (char *)NULL;

	strcpy(buf, q + 1);

	return buf;
}
```

for stuff like if statements the brace will be attatched but for functions it will not be attatched

**Comment by leo-arch** [comment]
I like it. Didn't know about clang-format, though I've compiled with clang before. So, let see if I get it:
We basically choose a source file as a formatting model for other source files (you suggest straft function?)

For what I've seen/read just now:
1) clang-format (at least its documentation) seems to be c++ oriented (but this doesn't seem to be any problem)
2) There's no Linux kernel style (though there is one for GNU, which is awful, btw), and this is why we should choose a custom source file as model instead.

Am I getting it right?

**Comment by leo-arch** [comment]
I like it. Didn't know about clang-format (tough I've compiled with clang before). So, _clang-format our formatting style file? I need to go deeper into it (there seems to be some disagreements with the current style, specially because there seems to be no Linux kernel style). I'll give it a try to inspect the output. I don't know exactly how the LLVM style behaves.

**Comment by leo-arch** [comment]
Nice! The disagreements are really only a few: max line length (should be set to 80 chars), and specially the way function's arguments are reordered (sometimes they go to the next line unnecessarily). However, clang-format brings a lot of options, so we should only play around with them a bit to get the formatting we want.

**Comment by leo-arch** [comment]
The results are generally fine, but I still can't find a way to properly handle multi-line statements, for example, this assignment (in colors.c):
ugly_format

**Comment by leo-arch** [comment]
Some issues I detected with the clang-format file:

1) This is the most important by far: by default, clang-format sorts the includes, which breaks the program. Solved adding "SortIncludes: false" to the formatting file.

2) (some) printf's and multi-line statements are not  properly formatted. I've manually modified source files.

**Pull request merged**
