### PR TITLE
Means of contact

### PR DESCRIPTION
**Pull request by comradekingu**
Also, https://github.com/leo-arch/isfree/pulls
Requested on #freerms, so I thought it to be within scope to get rid of that one too.

Edit: I don't like just asking for stuff, so maybe I can register the project on Hosted Weblate and throw in a nb_NO translation?

### CODE REVIEW

**Comment by leo-arch** [comment]
Hi @comradekingu. Could you please better explain what this PR is intended to exactly? I guess #freerms has something to do with Stallman. Is this PR pointing to `isfree` only, or is `clifm` involved as well? And what is an `nb_NO translation`?

**Comment by comradekingu** [comment]
Following the ousting of Stallman from the FSF, and the attempted justification of the reasons for it following his return, there is an IRC room (now on Libera) called #freerms. It just so happened that people there are very much in agreement when it comes to attacks on libre software. The Covenant text-document is a political tool, and positioned against meritocracy (as described by its author).

For what it should do, it doesn't, and is bloated at that. (Even more-so in the 2.0 version.) The most central flaw is that of writing unwritten rules, to the effect of things valuable enough to be put to writing, somehow would be thought now egregious to someone carrying it out, because they exist in a text-file.
The actual point of contact is valuable, but doesn't constitute a code of conduct. Also threw in a "welcome" to make it sound nice.

nb_NO is Norwegian Bokmål. The guy asked about `clifm`, but `isfree` is within scope too. Hoping to facilitate contributions, and will at-least do some myself, even if I don't use Arch.

**Comment by leo-arch** [comment]
Ok. I'll merge the PR.

About the translation, let me see if I got it correctly: this guy (he belongs to #freerms I guess) is offering a Norwegian translation of clifm (and isfree?). Only Norwegian? I see there are more languages in the Hosted Weblate page. Be it as it may, it's OK: contributions are always welcome.

What's the translation procedure. ¿Will the .pot file provided be me used (it is quite outdated btw)? Will the corresponding .mo files be send back via a PR?

**Comment by comradekingu** [comment]
@leo-arch The guy asking I told to contribute.
I am offering a nb_NO translation :)
There are many ways to set it up. #26

**Pull request merged**
