### PR TITLE
Make clifm logo an svg, add readme banner

### PR DESCRIPTION
**Pull request by Slackadays**
This should make the readme look nicer as well as make future branding easier :) If you want the banner to look different, then I can also change it.

### CODE REVIEW

**Comment by leo-arch** [comment]
Hey Slack, cool work!

As you surely already noted, I'm pretty bad at visual design stuff. I played with Inkscape some time ago (plus some Gimp) to design the SVG logo, at that was it. Never touched it again. So, thanks!

The banner is nice, I like it, it's refreshing. I guess I should replace the old Github card by this one.

I feel however that it takes to much screen in the README. But I think the size can be changed in the README file itself, without the need to modify the PNG, so, not a problem.

Btw, is there any difference between the old SVG logo and the new one?

**Comment by Slackadays** [comment]
The old SVG logo was actually a really junk bitmap, so not actually an SVG, so now that's fixed to be actual vector graphics instead. I can make the readme banner shorter so it doesn't take up so much space too. :)

**Comment by leo-arch** [comment]
> The old SVG logo was actually a really junk bitmap, so not actually an SVG

Good to know.

Wait, I remember it was possible to set the image size in the README itself (maybe html, don't remember). If this is possible, there's no need to touch the PNG file.

**Comment by Slackadays** [comment]
Adjusting the size of the PNG in the readme is going to make it not take up the whole width, so it's going to look like junk there unless the width is adjusted accordingly.

**Comment by Slackadays** [comment]
@leo-arch Actually, with this new not-quite-rectangular design, it should look good even when shrunk down, so go nuts there! :)

**Comment by leo-arch** [comment]
I think we should keep both.

**Comment by Slackadays** [comment]
Done, added a wide banner

**Comment by leo-arch** [comment]
Cool!

Having a few designs available allow us to later switch them according to our needs.

So, thank you very much again and merging.

**Pull request merged**
